# Generated by Django 4.0.4 on 2022-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_recorded_sales', models.IntegerField(blank=True)),
                ('total_amount_liters_discount', models.IntegerField(blank=True)),
                ('total_amount_of_deficit', models.IntegerField(blank=True)),
                ('total_amount_of_excess', models.IntegerField(blank=True)),
                ('total_amount_deposited', models.IntegerField(blank=True)),
                ('total_expenses', models.IntegerField(blank=True)),
                ('reported_date', models.CharField(max_length=255, null=True)),
                ('reported_time', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('gender_type', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('height_cm', models.IntegerField(blank=True)),
                ('weight_kl', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('birth_date', models.CharField(max_length=255, null=True)),
                ('start_date', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255, null=True)),
                ('date_in', models.CharField(max_length=255, null=True)),
                ('time_in', models.CharField(max_length=255, null=True)),
                ('date_out', models.CharField(max_length=255, null=True)),
                ('time_out', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('date_logged_in', models.CharField(max_length=255, null=True)),
                ('random_digit', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('in_charge', models.CharField(max_length=255, null=True)),
                ('item', models.CharField(max_length=255, null=True)),
                ('total_amount', models.IntegerField(blank=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_type', models.CharField(max_length=255, null=True)),
                ('kl', models.IntegerField(blank=True)),
                ('date_delivered', models.CharField(max_length=255, null=True)),
                ('time_delivered', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasoline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_type', models.CharField(max_length=255, null=True)),
                ('price_per_liter', models.IntegerField(blank=True)),
                ('previous_liter', models.IntegerField(blank=True)),
                ('latest_liter', models.IntegerField(blank=True)),
                ('total_liter', models.IntegerField(blank=True)),
                ('date_time_added', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_type', models.CharField(max_length=255, null=True)),
                ('in_charge', models.CharField(max_length=255, null=True)),
                ('liter_quantity', models.IntegerField(blank=True)),
                ('liter_price', models.IntegerField(blank=True)),
                ('total_amount', models.IntegerField(blank=True)),
                ('date_time_purchased', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, null=True)),
                ('item_price', models.IntegerField(blank=True)),
                ('no_of_items', models.IntegerField(blank=True)),
                ('date_time_added', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, null=True)),
                ('in_charge', models.CharField(max_length=255, null=True)),
                ('item_quantity', models.IntegerField(blank=True)),
                ('item_price', models.IntegerField(blank=True)),
                ('total_amount', models.IntegerField(blank=True)),
                ('date_time_purchased', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
