# Generated by Django 4.0.4 on 2022-05-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasPOSWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytotal',
            old_name='reported_date',
            new_name='date_time_reported',
        ),
        migrations.RemoveField(
            model_name='dailytotal',
            name='reported_time',
        ),
    ]
