# Generated by Django 4.0.4 on 2022-05-25 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GasPOSWeb', '0002_rename_reported_date_dailytotal_date_time_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytotal',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_cashier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_pumpboy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.employee'),
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.employee'),
        ),
        migrations.AddField(
            model_name='gasdelivery',
            name='gasoline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.gasoline'),
        ),
        migrations.AddField(
            model_name='gastransaction',
            name='gasoline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.gasoline'),
        ),
        migrations.AddField(
            model_name='itemtransaction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.item'),
        ),
        migrations.AlterField(
            model_name='expensestransaction',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.employee'),
        ),
        migrations.AlterField(
            model_name='gastransaction',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.employee'),
        ),
        migrations.AlterField(
            model_name='itemtransaction',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GasPOSWeb.employee'),
        ),
    ]
