# Generated by Django 4.0.4 on 2022-05-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasPOSWeb', '0004_remove_itemtransaction_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastransaction',
            name='gas_type',
        ),
    ]
