# Generated by Django 4.0.4 on 2022-05-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasPOSWeb', '0006_rename_password_employeelogin_date_logged_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelogin',
            name='token',
        ),
    ]
