# Generated by Django 4.0.4 on 2022-05-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasPOSWeb', '0008_rename_date_in_employeeattendance_datetime_logged_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_name',
        ),
    ]
