# Generated by Django 4.0.4 on 2022-05-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasPOSWeb', '0010_remove_gasoline_latest_liter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasdelivery',
            old_name='date_delivered',
            new_name='date_time_delivered',
        ),
        migrations.RemoveField(
            model_name='gasdelivery',
            name='gas_type',
        ),
        migrations.RemoveField(
            model_name='gasdelivery',
            name='time_delivered',
        ),
    ]
