# Generated by Django 4.0.4 on 2022-05-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GasPOSWeb', '0011_rename_date_delivered_gasdelivery_date_time_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensestransaction',
            old_name='date',
            new_name='date_time_expensed',
        ),
        migrations.RemoveField(
            model_name='expensestransaction',
            name='time',
        ),
    ]
